version: '3.7'

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - '****:****'

  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_REPLICA_HOST:
      MONGO_REPLICA_PORT:
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    ports:
      - *****:****
