version: '3.7'

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=shoofertaecommerce
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=35c9bc2d86cd68ca5b68a1330ab31b4
    ports:
      - '45432:5432'

  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 35c9bc2d86cd68ca5b68a1330ab31b4
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD:35c9bc2d86cd68ca5b68a1330ab31b4
    ports:
      - 56379:6379
